# Site settings

title: ishaq-zouaghi.fr
email: ishaq.zouaghi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    This is the personal website of Ishaq ZOUAGHI. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repo: https://github.com/IshaqZOUAGHI/ishaqzouaghi.github.io
repository: https://github.com/IshaqZOUAGHI/ishaqzouaghi.github.io
aboutme: Je suis <b>Ishaq ZOUAGHI</b> Ingénieur de Recherche en Informatique.
github_username: IshaqZOUAGHI

# Build settings
markdown: kramdown
plugins:
 - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true
      start_line: 1

# Author Info
# Author Info
author:
  name     : Ishaq ZOUAGHI
  image    : ./images/IshaqZ.png
  email    : ishaq.zouaghi@gmail.com
  github   : IshaqZOUAGHI
  twitter  : IshaqZOUAGHI
  linkedin : Ishaq ZOUAGHI

# Authors Info
authors:
  diabatem:
    name    : Mahamadou DIABATE
    website : https://twitter.com/DiabatMahamado1
  martinif:
    name    : Frédéric MARTINI
    website : https://www.developpez.net/forums/u1195/adiguba/

# Collections
collections:
  data-nosql:
    output: true
    permalink: /data-nosql/:name
  web:
    output: true
    permalink: /web/:name
  divers:
    output: true
    permalink: /divers/:name

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "divers"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "data-nosql"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Posts default Permalink
permalink: blog/:year/:month/:day/:title

# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
